apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubereport-role
rules:
  - apiGroups: [""]
    resources: 
      - namespaces 
      - pods
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
      - persistentvolumes
      - serviceaccounts
      - resourcequotas
      - limitranges
      - events
      - endpoints
      - nodes  # Added nodes here
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: 
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: 
      - ingresses
      - networkpolicies
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: 
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: 
      - storageclasses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: 
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: 
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: 
      - poddisruptionbudgets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: 
      - customresourcedefinitions
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
