apiVersion: v1
kind: Secret
metadata:
  name: kubereport-secret
  namespace: kubereport
type: Opaque 
data:
  {{- if .Values.smtp.enabled }}
  password: {{ .Values.smtp.password | b64enc }}
  {{- end }}
