{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.persistence.secretName }}
  namespace: kubereport
type: Opaque
data:
  {{- if .Values.persistence.secretValues }}
  {{- range $key, $value := .Values.persistence.secretValues }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}

